### PR TITLE
make it a Pytest plugin

### PR DESCRIPTION
**Pull request by thomasleveil**
This PR makes this python module compliant with [Pytest plugin requirements](https://docs.pytest.org/en/latest/writing_plugins.html#making-your-plugin-installable-by-others).

This way, users won't have to import the `httpx_mock` fixture explicitly

### CODE REVIEW

**Comment by Colin-b** [comment]
Thanks a lot this is great ! I tried to do this some time ago but struggled with the coverage, nicely done !

**Comment by thomasleveil** [comment]
regarding coverage, I had a stroke of luck, the second random thing I tried worked :stuck_out_tongue:

**Comment by Colin-b** [comment]
btw in case you missed it, it is available within version 0.4.0 release earlier today

**Comment by thomasleveil** [comment]
Excellent reactivity 😃

Le ven. 5 juin 2020 à 11:40, Colin Bounouar <notifications@github.com> a
écrit :

**Pull request merged**
