### PR TITLE
Setup httpx_mock via marker instead of fixtures

### LINKED ISSUE #137: Introduce decorators to setup httpx_mock
Right now only fixtures are available, making it impossible to change the overall behavior of the mock in between test cases.
This is currently worked around by separating tests in different files, based on the mock global settings. However it's not user-friendly enough, especially if those tests are essentially part of the same application context, thus belonging to the same test file / class.

### PR DESCRIPTION
**Pull request by RazerM**
Resolves #137

We want to be able to configure how the `httpx_mock` fixture behaves at different scopes. A pytest marker can be used at module, class, or test scope and so is what is used here.

Providing a non-default value from the fixtures will emit a DeprecationWarning for each test with the exact marker it can be replaced with:

```
=================================== warnings summary ===================================
tests/test_tmp.py::test_a
tests/test_tmp.py::test_b
  /.../pytest_httpx/__init__.py:56: DeprecationWarning: The assert_all_responses_were_requested and non_mocked_hosts fixtures are deprecated.
  Use the following marker instead:

  pytest.mark.httpx_mock(assert_all_responses_were_requested=False)

    warnings.warn(

tests/test_tmp.py::test_c
  /.../pytest_httpx/__init__.py:56: DeprecationWarning: The assert_all_responses_were_requested and non_mocked_hosts fixtures are deprecated.
  Use the following marker instead:

  pytest.mark.httpx_mock(non_mocked_hosts=['example.com'])

    warnings.warn(

```

### CODE REVIEW

**Comment by melanisti** [comment]
Guys, thank you so much for this pullrequest. It's a great library, but it's a feature it really lacks

**Comment by Colin-b** [comment]
I agree, I plan on looking to this as soon as I have some free time. hang in there

**Review by Colin-b — APPROVED** [review]
LGTM, thx again for the nice work. I will however drop the support for previous features, this is going to be a breaking change release anyway and changelog + readme document it well enough.

Really nice PR once again, it's refreshing to see actual clean code :)

**Comment by Colin-b** [comment]
This was released as part of version 0.31.0 today

**Comment by RazerM** [comment]
Thanks!

**Pull request merged**
