### PR TITLE
feature/get-response-methods

### PR DESCRIPTION
**Pull request by IliyaZinoviev**
- Add get_response and get_responses methods to have access to response objects related to requests
- Add _responses field handling to __init__, _handle_request, _handle_async_request and reset methods of HTTPXMock class.

### CODE REVIEW

**Comment by Colin-b** [comment]
Hello @IliyaZinoviev ,

Could you motivate this change please? Why would you need to access the responses ?

Thanks

**Comment by IliyaZinoviev** [comment]
> Hello @IliyaZinoviev ,
> 
> Could you motivate this change please? Why would you need to access the responses ?
> 
> Thanks

Good day, @Colin-b ! 

I'm testing some procedure: httpx request is called inside it and its response is mapped to testing procedure result. I wanna check that response data from the httpx request call is correctly mapped to procedure result data.

Now, I expose response data ouside testing procedure to test scope by this way:

```
from functools import partial
from typing import List

import httpx

def get_from_db(data):
    ...

def save_to_db(data):
    ...

def get_data_depends_on(data):
    ...

def some_procedure():
    with httpx.Client() as client:
        response = client.get("https://test_url")
    save_to_db(response.content)


def callback(
    container: List,
    request: httpx.Request,
) -> httpx.Response:
    data = get_data_depends_on(request)
    container.append(data)
    return httpx.Response(
        status_code=200,
        content=data,
    )


def test_some_procedure(httpx_mock):
    container = []
    cb = partial(callback, container)
    httpx_mock.add_callback(cb, url="https://test_url")

    some_procedure()
    assert get_from_db() == container[0]
```

But I want to use httpx_mock fixture like this:

```
import httpx

def get_from_db():
    ...

def save_to_db():
    ...

def get_data_depends_on():
    ...

def some_procedure():
    with httpx.Client() as client:
        response = client.get("https://test_url")
    save_to_db(response.content)


def callback(
    request: httpx.Request,
) -> httpx.Response:
    data = get_data_depends_on(request)
    return httpx.Response(
        status_code=200,
        content=data,
    )


def test_some_procedure(httpx_mock):
    httpx_mock.add_callback(callback, url="https://test_url")
    some_procedure()
    assert get_from_db() == httpx_mock.get_response().read()

```

PS. I hope you got my motivation and simplified code example 🙏🏼

**Comment by Colin-b** [comment]
As a test case should be deterministic, the code should know what to expect (what the response will contain as data in this context).

So instead of relying on some abstraction "whatever data is returned, it should have been processed this specific way and stored", the way I would do it is to explicitly check the expected data as in:

```python
def test_some_procedure(httpx_mock):
    httpx_mock.add_callback(callback, url="https://test_url")
    some_procedure()
    # You should know what the expected data should be at this point, and it should never change right?
    assert get_from_db() == expected_data
```

**Comment by Colin-b** [comment]
Closing as no response was received on the proposed alternative.

**Pull request closed without merging**
